### ISSUE TITLE
Should run in raw mode

### ISSUE THREAD

**Issue by Ingo60** [tfausak/fr2048#1]
Program should run in raw mode. For example, you should run

    stty raw -echo

at the beginning, and 

    stty -raw echo

at the end, and inbetween draw the board at a fixed screen position.

**Comment by tfausak** [comment]
> should run in raw mode 

You're absolutely right. Check out [these lines](https://github.com/tfausak/fr2048/blob/v1.0.0/fr2048/Main.fr#L48-L49). In Haskell I was able to use `hSetBuffering` and `hSetEcho`. As far as I can tell, there is no equivalent in Frege or Java. I'm alright with running shell commands before and after running fr2048, but they're not very portable.

> draw the board at a fixed screen position 

I think something like [JCurses](http://sourceforge.net/projects/javacurses/) is the real answer, but I didn't want to sink that much time into it.

**Comment by Ingo60** [comment]
If you're ok with it, I'll do a pull request when I find the time.

**Comment by tfausak** [comment]
:+1: for sure!
